### ISSUE TITLE
OSX Build

### ISSUE THREAD

**Issue by rolox** [hughperkins/EasyCL#10]
I tried to build EasyCl on OS X 10.10.4, and it seems to build and work so far. 
But, I've installed MacPorts before trying it, what means there may be some dependencies that I already had solved in advance.

So maybe you could add OS X as a possible target the README file.

**Comment by hughperkins** [comment]
Hi rolox, yes in theory it should build on mac.  And I try to provide support for mac builds.  They're a bit hit and miss though for now...

**Comment by rolox** [comment]
Thx
