### ISSUE TITLE
Feature Request: Simple check to see which vendor we're on

### ISSUE THREAD

**Issue by merceyz** [hughperkins/EasyCL#22]
A simple function to see if we're on AMD, Nvidia, Intel, or other. (To use with DeepCL)

Reason: Nvidia prefers workgroupsizes to be a multiple of 32, AMD prefers 64 and Intel (CPU) 8
So it would be nice to easily see which platform we're currently on

**Comment by hughperkins** [comment]
Hi Chris,

Cool :-) . Actually, you can get this as follows:
```
    int numGpus = DevicesInfo::getNumGpus();
    for(int i = 0; i < numGpus; i++) {
        cout << DevicesInfo::getGpuInfo(i).toString() << endl;
    }
```
Or, this will print:
```
... stuff...
platformVendor: Apple
platformName: Apple
...
deviceName: AMD Radeon Pro 450 Compute Engine
... 
```
To get the value of platformVendor:
```
        cout << DevicesInfo::getGpuInfo(i).platformVendor << endl;
```

You can take a look at:
- the test script at https://github.com/hughperkins/EasyCL/blob/f1a92835a28d05cd220e6ed25f878aaf35cf4d87/test/testDeviceInfo.cpp#L17-L20
- DeviceInfo.h, at https://github.com/hughperkins/EasyCL/blob/f1a92835a28d05cd220e6ed25f878aaf35cf4d87/DeviceInfo.h#L26-L41

**Comment by merceyz** [comment]
How would that work if I only have a EasyCL* and CLKernel* 
https://github.com/hughperkins/DeepCL/blob/master/src/conv/BackpropWeightsScratch.cpp#L56

**Comment by hughperkins** [comment]
The methods above are static. Global. Dont need any EasyCL or CLKernel objects.  Just call these global methods directly.

**Comment by hughperkins** [comment]
(though you probably want to cache the result, if you're going to be checking this value thousands of times a second)

**Comment by merceyz** [comment]
Yes, that was the plan.

Though I want to know it for the specific device the kernel will be run on (the line I linked to).
So I either need to get the device ID from the CL object or `easycl::DevicesInfo::getDeviceInfo` needs to accept a cl_device_id object

**Comment by hughperkins** [comment]
Seems you can get the DeviceInfo from the cl like this: https://github.com/hughperkins/clnn/blob/master/lib/THCLNN/im2col.cpp#L19

```
  int maxWorkgroupSize = ((easycl::DeviceInfo *)state->deviceInfoByDevice[state->currentDevice])->maxWorkGroupSize;
```

**Comment by hughperkins** [comment]
oh wait, thats torch specific. hmmm

**Comment by hughperkins** [comment]
Hmmm, ok I see.  So, getting the device_id and platform_id from the EasyCL object is already possible:

https://github.com/hughperkins/EasyCL/blob/master/EasyCL.h#L65-L66
```
    cl_platform_id platform_id;
    cl_device_id device;
```
But there's no obvious existing method to then retrieve a DeviceInfo object given those.

**Comment by merceyz** [comment]
It can be done like this:
```
easycl::DeviceInfo info;
info.populate(cl->platform_id, cl->device);

cout << info.platformVendor << endl;
```

Thanks for pointing me in the right direction

**Comment by hughperkins** [comment]
Cool :-)
