### ISSUE TITLE
CLKernel::run calls do not wait for completion

### ISSUE THREAD

**Issue by doe300** [hughperkins/EasyCL#25]
In method `CLKernel::run(cl_command_queue *queue, int ND, const size_t *global_ws, const size_t *local_ws)`, the call to `clEnqueueNDRangeKernel` in line 332 does not wait for completion. This can cause wrong result being read into the output buffers.

**Comment by iame6162013** [comment]
@hughperkins do you want me to make a pr? 
Because I'm also getting this issue, I've looked at the source code, and clEnqueueReadBuffer does not wait for clEnqueueNDRangeKernel.
