### ISSUE TITLE
Problem with lua version when compiling on Archlinux

### ISSUE THREAD

**Issue by mpiffault** [hughperkins/EasyCL#3]
Hi,
firstly thank you for you're work on this. Actually I'm trying to compile EasyCL to use with cltorch.

On archlinux, the last and default version of lua is 5.3.
The 5.1 version is still in the package, and if installed, it's well recognized at cmake time : 

```
$ cmake ..
-- The C compiler identification is GNU 5.1.0
-- The CXX compiler identification is GNU 5.1.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Setting build type to 'Release'
-- Found Lua51: /usr/lib64/liblua5.1.so;/usr/lib64/libm.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/libraries/EasyCL/build
```

But at compile time, I got those messages :

```
[ 13%] Building CXX object CMakeFiles/EasyCL.dir/templates/LuaTemplater.cpp.o
/home/user/libraries/EasyCL/templates/LuaTemplater.cpp: In constructor 'LuaTemplater::LuaTemplater()':
/home/user/libraries/EasyCL/templates/LuaTemplater.cpp:28:18: error: 'lua_open' was not declared in this scope
     L = lua_open();
                  ^
/home/user/libraries/EasyCL/templates/LuaTemplater.cpp: In member function 'void LuaTemplater::set(std::string, std::string)':
/home/user/libraries/EasyCL/templates/LuaTemplater.cpp:41:21: error: 'LUA_GLOBALSINDEX' was not declared in this scope
     lua_setfield(L, LUA_GLOBALSINDEX, name.c_str());
                     ^
/home/user/libraries/EasyCL/templates/LuaTemplater.cpp: In member function 'void LuaTemplater::set(std::string, float)':
/home/user/libraries/EasyCL/templates/LuaTemplater.cpp:45:21: error: 'LUA_GLOBALSINDEX' was not declared in this scope
     lua_setfield(L, LUA_GLOBALSINDEX, name.c_str());
                     ^
/home/user/libraries/EasyCL/templates/LuaTemplater.cpp: In member function 'void LuaTemplater::set(std::string, std::vector<std::basic_string<char> >&)':
/home/user/libraries/EasyCL/templates/LuaTemplater.cpp:53:21: error: 'LUA_GLOBALSINDEX' was not declared in this scope
     lua_setfield(L, LUA_GLOBALSINDEX, name.c_str());
                     ^
/home/user/libraries/EasyCL/templates/LuaTemplater.cpp: In member function 'void LuaTemplater::set(std::string, std::vector<int>&)':
/home/user/libraries/EasyCL/templates/LuaTemplater.cpp:61:21: error: 'LUA_GLOBALSINDEX' was not declared in this scope
     lua_setfield(L, LUA_GLOBALSINDEX, name.c_str());
                     ^
/home/user/libraries/EasyCL/templates/LuaTemplater.cpp: In member function 'void LuaTemplater::set(std::string, std::vector<float>&)':
/home/user/libraries/EasyCL/templates/LuaTemplater.cpp:69:21: error: 'LUA_GLOBALSINDEX' was not declared in this scope
     lua_setfield(L, LUA_GLOBALSINDEX, name.c_str());
                     ^
CMakeFiles/EasyCL.dir/build.make:238: recipe for target 'CMakeFiles/EasyCL.dir/templates/LuaTemplater.cpp.o' failed
make[2]: *** [CMakeFiles/EasyCL.dir/templates/LuaTemplater.cpp.o] Error 1
CMakeFiles/Makefile2:95: recipe for target 'CMakeFiles/EasyCL.dir/all' failed
make[1]: *** [CMakeFiles/EasyCL.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```
I'm not at all comfortable with cpp compilation, but it seems that there's a problem with lua_open(), and as I see [here](http://www.lua.org/manual/5.1/manual.html), lua_open seems deprecated as for 5.1, and so removed as soon as 5.2 version (As stated [here - chapter 8](http://www.lua.org/manual/5.2/manual.html)).
So what I understand is that the files included are those of lua 5.3, not 5.1. Would it be any way to configure that more precisely ?

**Comment by mpiffault** [comment]
Actually I confirmed this by prefixing imports like this :

```
extern "C" {
    #include "lua5.1/lua.h"
    #include "lua5.1/lualib.h"
    #include "lua5.1/lauxlib.h"
}
```
This way it builds without error.

**Comment by hughperkins** [comment]
Ah... so your current idea is, add 'lua5.1' prefix to the lua imports?  (I havent thought this through, just now read your notificaoitn, about 30 seconds ago.  Off the top of my head, other possibilities would seem to be:
- somehow make the code work for all versions, 5.1-5.3
- somehow control the include path, so it only picks up 5.1 (eg shift it to the front)
- modify code to use 5.2/5.3 instead
- ... ? )

**Comment by hughperkins** [comment]
on my system, I do in fact also have lua include files in lua5.1 diretory (on ubuntu), so adding prefix would owkr on my system, which is a good start :-)  Do you know of any references which state, or provide good evidence for, there always being a lua5.1 directory?  (An appropriate line in install section in a makefile in defualt lua could be sufficient evidence I guess?)

**Comment by hughperkins** [comment]
As it happens, I have the sourcecode for lua 5.1
- INSTALL document says that `make install`, from the makefile is the standard
- Makefile says 'see INSTALL document' for details about install
- I cant seem to find where in Makefile that `install` is defined.  is it a default Makefile target perhaps?  I dont see the string `5.1` anywhere, in a search.

**Comment by hughperkins** [comment]
Ok, I was looking at wrong Makefile.  So I did this:
```
make install INSTALL_TOP=/tmp/lua-inst
```
Result was that /tmp/lua-inst/include contained:
```
ls /tmp/lua-inst/include/
lauxlib.h  luaconf.h  lua.h  lua.hpp  lualib.h
```
Seems like lua5.1 is not a part of standard lua include path?

**Comment by hughperkins** [comment]
installing lua5.2 on my system. will have a play :-)

**Comment by hughperkins** [comment]
Hmmm, builds for me, on ubuntu, with lua5.2 installed.  will prod the install a bit..

**Comment by hughperkins** [comment]
You know, one option could be, I put the lua5.1 sourcecode in the EasyCL repository, can put the include files in a lua5.1 subdirectory as well, and then it should be nice and controlled I guess?  Thoughts on this?  I guess it might add ~1MB to the git clone?

**Comment by hughperkins** [comment]
Replaced `lua_open` with `luaL_newstate` (which was an alias to in 5.1 anyway)
- pushed this change to EasyCL master branch
- pushed the EasyCL change to cltorch master branch

**Comment by mpiffault** [comment]
Works well.
For the mising LUA_GLOBALSINDEX, the solution is to use lua_setglobal().

Replacing
```lua_setfield(L, LUA_GLOBALSINDEX, name.c_str())```
by
 ```lua_setglobal(L, name.c_str())```

it compiles without problem on lua 5.2/5.3. It seems it compiles well on 5.1 too.

Oh and you pushed on the ```experimentally-modify-waitevents```.

**Comment by hughperkins** [comment]
> Oh and you pushed on the experimentally-modify-waitevents.

Hmmm, right. updated my comment.

> For the mising LUA_GLOBALSINDEX, the solution is to use lua_setglobal().

Ok, updated.
