### ISSUE TITLE
copyToHost failure for intel cpu device

### ISSUE THREAD

**Issue by xonobo** [hughperkins/EasyCL#7]
I managed to run an opencl kernel on intel hd graphics 2500 but when I changed the device to CPU the program crashes at a copyToHost call (for an output buffer named out) after the kernel run, without any error print. Visual studio says "unhandled exception ... access violation writing location ...". 

When I commented everything about variable out in the kernel the program passes the copyToHost call without any error. But interestingly when I put just this line it crashes again

out[0] = 0.0f

Can you advise any debugging methodolgy for this case?
I guess I have a problem with the memory buffer on the host side but it runs perfectly for the GPU case.

Thanks in advance.

**Comment by hughperkins** [comment]
Are you sure you're writing off the end of the buffer?  Did you try with a very simple kernel that only writes at position [0] of the buffer?  Or writes nothing at all in fact perhaps?

**Comment by xonobo** [comment]
Here is my test kernel. It copies an image buffer to a local memory buffer and then tries to write a zero to output buffer. It runs perfectly on HD grahics but crashes at copyToHost call for the output buffer. When I commented out the image patch copying to local memory then it runs perfectly both on CPU and GPU.

Any idea?

// CPU test kernel
kernel void testCPU(		   const int imageW
							 , const int imageH
							 , global float *inputImage
							 , const int patchW
							 , const int patchH
							 , const int extension
							 , local float *tempPatch
							 , global float *output
 )
 {
	const int groupId = get_group_id(0);
	const int localId = get_local_id(0);
 
    const size_t numGroups = get_num_groups(0);
	const size_t numLocalWorkItems = get_local_size(0);
	
	const int groupDim_x = ceil( (float)imageW / (float)patchW );
	const int groupDim_y = ceil( (float)imageH / (float)patchH );
	//assert(groupDim_x*groupDim_y == numGroups);
	
	const int x0 = (groupId % groupDim_x) * patchW - extension;
	const int y0 = (groupId / groupDim_x) * patchH - extension;
	const int patchW_ext = patchW + 2*extension;
	const int patchH_ext = patchH + 2*extension;

	/**/
	/////////////////////////////////////////////////////////////
	// Copy image patch to local memory /////////////////////////
	const int numPixToCopy = patchW_ext*patchH_ext;
	const int copyPointsPerWorkItem = ceil( (float)numPixToCopy / (float)numLocalWorkItems );	
	for (int n=0; n<copyPointsPerWorkItem; ++n)
	{
		const int pixId = n*numLocalWorkItems + localId;
		
		// Convert to x and y for destination
		const int dstX = pixId%patchW_ext;
		const int dstY = pixId/patchW_ext;

		// Convert to x and y for source
		const int srcX = x0 + dstX;
		const int srcY = y0 + dstY;

		// Copy to local
		if (srcX >= 0 && srcX < imageW && srcY >= 0 && srcY < imageH )
			tempPatch[pixId] = inputImage[srcY*imageW + srcX];
		else
			tempPatch[pixId] = 0;
	}

	barrier(CLK_LOCAL_MEM_FENCE);	
	/////////////////////////////////////////////////////////////
	/**/


	if (localId==0 && groupId==0)
		output[0] = 0.0f;		
	barrier(CLK_LOCAL_MEM_FENCE);

}

**Comment by hughperkins** [comment]
I think you probably want to find the simplest possible kernel with the issue.  What happens if have a local array of 1 single float, and update the value of just that one float?  What if you have 1k of local floats, and update that? etc?

**Comment by xonobo** [comment]
I found that I have accesses to memory locations out of bounds. Now CPU also works perfectly. Thanks for your help and this excellent library.

**Comment by hughperkins** [comment]
Ok great!
