### ISSUE TITLE
conflicting declerations for int64 and uint64 with opencv 2.4.10

### ISSUE THREAD

**Issue by xonobo** [hughperkins/EasyCL#8]
I have a project which utilize both opencv and EasyCL. It compiles and runs on windows (visual studio), but on linux it complains about conflicting declerations for int64 and uint64.

at opencv side:
typedef int64_t int64
typedef uint64_t uint64

and at EasyCL side:
typedef long long int int64
typedef long long unsigned int uint64

Do you have any advice for this problem?
http://stackoverflow.com/questions/4416932/typedef-redefinition-c2371-for-uint32-in-two-3rd-party-libraries
At this link it is adviced to use namespaces but I see that easycl namespace is already defined. Is there a way to avoid this conflict by using namespaces cv and easycl?
Thanks in advance.

**Comment by hughperkins** [comment]
Hmmm. their typedef is more correct.  I will check that int64_t and uint64_t are available in gcc/g++ 4.4, and in visual studio 2008, and if so, I will think about how to change the typedef.

**Comment by hughperkins** [comment]
Hi Xonobo, I've created a branch called `uint64_t`, which replaces int64 and uint64 with int64_t and uint64_t, so now there will be no conflict.  Can you try this branch and let me know if it works ok for you?  I'm trying some experiments with my own projects too, and if it looks ok, I'll merge it to master.

**Comment by xonobo** [comment]
Is it ok that I clone the branch and paste it into source folder of OpenCL in cltorch and rebuild the cltorch? In order to avoid multiple instances of libraries I use OpenCL libraries builded in the torch-distro via cltorch. 

Otherwise I can try it with a sole OpenCL build.

**Comment by hughperkins** [comment]
Hi Xonobo, ok, I've also updated cltorch now, to migrate from using uint64/uint32 to using uint64_t/uint32_t, in branch `uint64_t`, of cltorch.

**Comment by xonobo** [comment]
I recursively cloned the uint64_t barnch of cltorch and EasyCL and then copied EasyCL to cltorch/src/EasyCL folder. Build the cltorch by luarocks smoothly.

Then tried to compile my project with opencv and got this error.
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

Changed the compiler dialect on eclipse to 
GCC C++ Compiler -> Dialect -> ISO C++11 (-std=c++0x)

The project compiled and run ok.

I also tried the torch side. But could not load the cltorch. It complains about loading the .so file but the fresh libcltorch.so exist at that location.

th> require('cltorch')
/torch/install/share/lua/5.1/trepl/init.lua:363: /torch/install/share/lua/5.1/cltorch/init.lua:19: cannot load '/torch/install/lib/lua/5.1/libcltorch.so'
stack traceback:
	[C]: in function 'error'
	/torch/install/share/lua/5.1/trepl/init.lua:363: in function 'require'
	[string "_RESULT={require('cltorch')}"]:1: in main chunk
	[C]: in function 'xpcall'
	/torch/install/share/lua/5.1/trepl/init.lua:630: in function 'repl'
	/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
	[C]: at 0x00406670

**Comment by hughperkins** [comment]
Hmmm, right.  I have the same error.  That's odd.

**Comment by hughperkins** [comment]
Hmmmm: `ImportError: No module named 'libstdcxx'`

**Comment by hughperkins** [comment]
I quickly tried to fix it.  Not very tested yet, but I've pushed to the branch, in cltorch, if you want to try?

**Comment by hughperkins** [comment]
Try now?

**Comment by xonobo** [comment]
I just tried it before your last comment and it was also ok :)

**Comment by hughperkins** [comment]
Cool :-)  (I changed nothing, just tested it a bit more :-) )  So, can close the issue?

**Comment by xonobo** [comment]
ok, thanks a lot.

**Comment by hughperkins** [comment]
cool :-)
