### ISSUE TITLE
gpuinfo lists two device but I can see only one device from a C++ app.

### ISSUE THREAD

**Issue by xonobo** [hughperkins/EasyCL#9]
I am trying to assign the intel CPU as the opencl device on linux. I am using the uint64_t branch of EasyCL and cltorch. I could not list the intel device in my C++ project. It only lists nvidia device. In order to list the devices I just call gpuinfo.cpp code snippet in a function.

However when I call the gpuinfo executable in a bash I see both devices as given at the bottom.

I remember that cltorch does not support CPU devices. That's why I get rid of any source code related with torch in my C++ project to give a try but now I get these linker errors:

/torch/install/lib/libEasyCL.so: undefined reference to `lua_createtable'

/torch/install/lib/libEasyCL.so: undefined reference to `lua_rawseti'

/torch/install/lib/libEasyCL.so: undefined reference to `lua_getfield'

/torch/install/lib/libEasyCL.so: undefined reference to `luaL_loadstring'

/torch/install/lib/libEasyCL.so: undefined reference to `luaL_newstate'

/torch/install/lib/libEasyCL.so: undefined reference to `luaL_openlibs'

/torch/install/lib/libEasyCL.so: undefined reference to `lua_pushnumber'

/torch/install/lib/libEasyCL.so: undefined reference to `lua_pcall'

/torch/install/lib/libEasyCL.so: undefined reference to `lua_close'

/torch/install/lib/libEasyCL.so: undefined reference to `lua_pushstring'

/torch/install/lib/libEasyCL.so: undefined reference to `lua_settop'

/torch/install/lib/libEasyCL.so: undefined reference to `lua_setfield'

/torch/install/lib/libEasyCL.so: undefined reference to `lua_tolstring'

collect2: error: ld returned 1 exit status

Any idea?

bozkalayci@bozkalayci-WS-Linux:/torch/cltorch$ /torch/cltorch/build/EasyCL/src/EasyCL-external-build/gpuinfo
num platforms: 2

platform index: 0:
platform id: 0xe7a190
platform vendor: Intel(R) Corporation
platform name: Intel(R) OpenCL
platform num devices: 1

   device index: 0
   device id: 0xe7b408
   device type: 2
   global memory size: 64358MB
   local memory size: 32KB
   global cache size: 256KB
   global cacheline size: 64
   max memory alloc size: 16089MB
   max compute units: 32
   max workgroup size: 8192
   max workitem dimensions: 3
   max workitem sizes: 8192 8192 8192
   device name:        Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
   opencl c version: OpenCL C 1.2 
   opencl device version: OpenCL 1.2 (Build 43)
   frequency MHz: 2000

platform index: 1:
platform id: 0xe86000
platform vendor: NVIDIA Corporation
platform name: NVIDIA CUDA
platform num devices: 1

   device index: 0
   device id: 0xe860c0
   device type: 4
   global memory size: 509MB
   local memory size: 47KB
   global cache size: 16KB
   global cacheline size: 128
   max memory alloc size: 128MB
   max compute units: 1
   max workgroup size: 1024
   max workitem dimensions: 3
   max workitem sizes: 1024 1024 64
   device name: Quadro 410
   opencl c version: OpenCL C 1.1 
   opencl device version: OpenCL 1.1 CUDA
   frequency MHz: 705

**Comment by xonobo** [comment]
Changing the order of libaries solved the linker error. Now I can run my executable.

However still I can not see the intel device from my C++ project, but it is listed by gpuinfo on bash terminal. Any idea?

**Comment by hughperkins** [comment]
Ok.   How are you obtaining the devices in your c++ project?  Can you paste the relevant few lines below?

**Comment by xonobo** [comment]
I guess I manage to replicate the odd behaviour. When I use easyCL alone I got two devices listed. But when I add a simple opencv related code to project I lost the CPU device. I created a demo eclipse project 

https://github.com/xonobo/myGpuInfo

When I commented out the matrix initialization of opencv at line 22 only GPU device is listed.

I want to remind that opencv also have some opencl staff.

Any idea to overcome this problem?

**Comment by hughperkins** [comment]
Can you initialize clew first?  ie put the line ` bool clpresent = 0 == clewInit();` at the start of the `main` function.

**Comment by xonobo** [comment]
I moved the opencv matrix initialization just before the last return but it did not help. Now I am trying to upgrade the opencv 2 to 3. Will share the results.

**Comment by hughperkins** [comment]
> I moved the opencv matrix initialization just before the last return

Hmmm, what do you mean?  Can you show me the sourcecode?

**Comment by xonobo** [comment]
I updated the code here

https://github.com/xonobo/myGpuInfo/blob/master/gpuinfo.cpp

**Comment by hughperkins** [comment]
So, you uncomment out line 88, and that affects the results of running lines 21 to 85?

**Comment by hughperkins** [comment]
Oh ... one thing to check... make sure that opencv isnt linking with opencl somehow.  Like, for clblas, which links with opencl, or wants to, I feed in clew to clblas, and tell it 'hey, this clew, it's actually opencl', and then it works ok.

**Comment by xonobo** [comment]
No, I mean 

line 88 commented: 2 devices
line 88 commented out: 1 device

**Comment by hughperkins** [comment]
Here is an example of feeding clew to clblas.  I guess you might be able to do something similar for opencv?  https://github.com/hughperkins/cltorch/blob/master/src/CMakeModules/build_clBLAS.cmake#L22-L23

**Comment by xonobo** [comment]
Hmm, I am sure that opecv libraries are linked with opencl. So if I want to use opencv with easyCL I have to use an opencv library that compiled without opencl, right?

**Comment by hughperkins** [comment]
> No, I mean
> 
> line 88 commented: 2 devices
> line 88 commented out: 1 device

yes, understood.  I imagine it affects the linking process somehow, since suddenly you're linking with some additional functions, from opencv, and thus with all the other things that opencv itself links with, ie pluasibly opencl.

**Comment by xonobo** [comment]
I will try to make clew as the opencl engine of opencv. But now it is easier to remove opencl from opencv and go on my project. I will share the results in building opencv via clew. 

I am closing the issue for now. Thanks again for your help and concern.

**Comment by hughperkins** [comment]
Hmmm, actually, another approach would be for me to provide an option in easycl to link directly with opencl, not use clew.  That wouldnt be hard to do actually.  Let me know if this could be useful to you.

**Comment by xonobo** [comment]
It would be great :)

**Comment by hughperkins** [comment]
Ok.  Can you try branch `clew-optional` of EasyCL please?  Set option `USE_CLEW` to `OFF` in ccmake.

**Comment by xonobo** [comment]
thanks for the quick return but I can try it on monday at work :(

**Comment by hughperkins** [comment]
ah :-P

**Comment by xonobo** [comment]
I builded the libeasycl.so library with USE_CLEW=OFF. When I check ldd libEasyCL.so command now I see libOpenCL.so instead of libclew.so. But my project still can not list cpu device. I also removed clew library from linking but have no idea what's wrong.

**Comment by hughperkins** [comment]
> But my project still can not list cpu device.

Oh, that's normal, since I make cltorch only list gpu devices, not cpu devices.  But the Quadro is a GPU right?

**Comment by hughperkins** [comment]
Hmmm... oh wait... easycl, not cltorch.  easycl should show you all devices, if you ask it for all devices.  But I have to rush off for a bit.  Will check a bit less rushed a bit later...

**Comment by hughperkins** [comment]
Hmmm... odd... but now it's basically pure OpenCL code.  Oh, you are stil including clew.h, can you remove that include, if you didnt already?

**Comment by xonobo** [comment]
Yes, I removed the clew.h but didn't work. Interesting?

**Comment by hughperkins** [comment]
I'm not sure.  I think it would need someone to look in detail at what opencv is doing.  But I dont have time for that right now :-(

**Comment by xonobo** [comment]
ok thanks a lot for your efforts. I am happy with easycl. It's opencv's turn now :)

**Comment by hughperkins** [comment]
:-)
